version: '3.1'
services:
  nginx:
    image: nginx:latest
    ports:
      - '80:80'
      - '443:443'
    restart: unless-stopped
    volumes:
      - /root/study-mbti/dist:/usr/share/nginx/html
      - ./nginx:/etc/nginx
      - ./certbot/conf:/etc/nginx/ssl
      - ./certbot/data:/var/www/certbot

  certbot:
    image: certbot/certbot:latest
    command: certonly --webroot --webroot-path=/var/www/certbot --email wil953742@gmail.com --agree-tos --no-eff-email -d studymbti.shop
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/logs:/var/log/letsencrypt
      - ./certbot/data:/var/www/certbot
